### ISSUE TITLE
eth_call    Received invalid block tag 10. Latest block number is 5

### ISSUE THREAD

**Issue by aspandyar** [aspandyar/DSSP#7]
While call any blockchain functions on frontend: 
buyStorage or any other, but look at **buyStorage** now
```js
const response = await contract.methods
        .buyStorage(fileMetadata)
        .send({ from: account, value: totalCost });
```

I got following error on hardhat node:
```bash
eth_call

  Received invalid block tag 10. Latest block number is 5
```

In blockchain getting zero account info:

```json
{
            "id": "0",
            "size": "0",
            "serverIds": [],
            "blockHashes": [],
            "name": "",
            "user": "0x0000000000000000000000000000000000000000"
        }
```

Also in metamask pop up, I am getting pending request of call function:

![image](https://github.com/user-attachments/assets/70fe3493-84e1-4b28-bbad-1b69eb4fa725)

no cleaning and reset any data from metamask, blockchain and other block helping here. But backend functions call with same function, work: runner.js, buyStorage.js
```js
await storageContract.methods.buyStorage(fileMetadata).send({
        value: totalCost,
        from: publicKey,
    });
```
work fine

**Comment by aspandyar** [comment]
Branch: Frontend:latest

Make sure to init .env file with:

HARDHAT_URL=http://127.0.0.1:8545
CONTRACT_ADDRESS=0x5FbDB2315678afecb367f032d93F642f64180aa3
REACT_APP_HARDHAT_URL=http://127.0.0.1:8545
REACT_APP_CONTRACT_ADDRESS=0x5FbDB2315678afecb367f032d93F642f64180aa3

**Comment by aspandyar** [comment]
NOTE: address are not **REAL**!!! They all local

**Comment by merura** [comment]
That's a metamask + hardhat issue
It cannot be fixed, just clear activity, remove and add hardhat local network, reinstall metamask, reinstall browser XD
